### ISSUE TITLE
关于您2021年在“Pattern Recognition”期刊上发表的一篇名为“Attribute and instance weighted naive Bayes”文章的问题

### ISSUE THREAD

**Issue by Bigdata-Development** [zhanghuan1994/homepage#1]
您好，我是您的一个读者，我对您2021年在“Pattern Recognition”期刊上发表的一篇名为“Attribute and instance weighted naive Bayes”的文章中所提出的AIWNBE和AIWNBL算法存在一些疑惑，请问您可以提供一下关于此篇文章的源码吗？

**Comment by zhanghuan1994** [comment]
你好，由于我不是本文的通讯作者，如您有任何疑问，请与本文的通讯作者蒋教授联系，谢谢。 













--

祝您工作愉快！
张欢
中国地质大学（武汉）计算机学院2020级博士




在 2022-03-04 11:28:08，"Bigdata-Development" ***@***.***> 写道：

您好，我是您的一个读者，我对您2021年在“Pattern Recognition”期刊上发表的一篇名为“Attribute and instance weighted naive Bayes”的文章中所提出的AIWNBE和AIWNBL算法存在一些疑惑，请问您可以提供一下关于此篇文章的源码吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bigdata-Development** [comment]
感谢您的回复，祝您生活愉快！
